<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 02: Evaluate the Summer Olympics, London 2012 dataset

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: View and add the dataset

In [2]:
#Import the necessary library
import numpy as np

In [3]:
#Manually add the Summer Olympics, London 2012 dataset as arrays
np_olympic_country = np.array(['GBR','CHN','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver=np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze=np.array([19,22,32,29,7,17,14])


#### Find the country with maximum gold medals

In [4]:
#Use the argmax() method to find the highest number of gold medals
max_gold_index=np_olympic_country_Gold.argmax()

In [5]:
#Print the name of the country
max_gold_index

3

In [7]:
country_with_max_gold=np_olympic_country[max_gold_index]
print(country_with_max_gold)

US


#### Find the countries with more than 20 gold medals

In [9]:
#Use Boolean indexing technique to find the required output
more_than_20_indicies=np_olympic_country_Gold>20
more_than_20_indicies

array([ True,  True,  True,  True, False, False, False])

In [10]:
country_with_20more=np_olympic_country[more_than_20_indicies]
print(country_with_20more)

['GBR' 'CHN' 'RUS' 'US']


#### Evaluate the dataset and print the name of each country with its gold medals and total number of medals

In [15]:
#Use a for loop to create the required output
for i in range(len(np_olympic_country)):
    gold_medal = np_olympic_country_Gold[i]
    country=np_olympic_country[i]
    total_model=np_olympic_country_Gold[i]+np_olympic_country_Silver[i]+np_olympic_country_Bronze[i]
    print('{}, gold Medal {}, Total Medals {}'.format(country,gold_medal,total_model))

GBR, gold Medal 29, Total Medals 65
CHN, gold Medal 38, Total Medals 88
RUS, gold Medal 24, Total Medals 81
US, gold Medal 46, Total Medals 103
KOR, gold Medal 13, Total Medals 28
JPN, gold Medal 7, Total Medals 38
GER, gold Medal 11, Total Medals 36


In [16]:
ar1=[1,0.3, 8, 6.4]

In [17]:
npar1=np.array([1,0.3, 8, 6.4])

In [18]:
npar2=np.array([3.14j, 7.3j, 5.1j. 2])

SyntaxError: invalid syntax (<ipython-input-18-2d32d05eeeb6>, line 1)

In [28]:
x = np.ones((5,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
x.transpose()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])